# Generated by Django 3.0.2 on 2022-03-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sandbox', models.BooleanField(db_index=True, default=False)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('notification_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
            managers=[
                ('notifications', django.db.models.manager.Manager()),
            ],
        ),
    ]
