# Generated by Django 3.0.2 on 2022-03-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.IntegerField(blank=True, choices=[('1', 'Stationary'), ('2', 'Upwards'), ('3', 'Decline')], null=True),
        ),
    ]
